
import makeup from "@/assets/makeup.png";
import fire from '@/assets/fire.png';
import ship from '@/assets/ship.png';
import eye from '@/assets/eye.png'

export const profileData = [
  { id: 1, img: makeup, beauty: "Beauty & Fashion", title: "The impact of beauty products on self esteeem of individuals", story: ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolores nihil suscipit ullam amet voluptatibus laboriosam est hic beatae obcaecati perferendis earum explicabo dolorem, maxime, quidem officiis sequi modi aspernatur maiores fugit rerum eos null  temporibus. Quam exercitationem amet, repellat doloribus inventore quod delectus non suscipit, doloremque, rem excepturi dolor. Lorem ipsum dolor sit amet consectetur.` },
  { id: 2, img: fire, beauty: "History", title: "The evolution of fire", story: ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolores nihil suscipit ullam amet voluptatibus laboriosam est hic beatae obcaecati perferendis earum explicabo dolorem, maxime, quidem officiis sequi modi aspernatur maiores fugit rerum eos null  temporibus. Quam exercitationem amet, repellat doloribus inventore quod delectus non suscipit, doloremque, rem excepturi dolor. Lorem ipsum dolor sit amet consectetur.` },
  { id: 3, img: ship, beauty: "Lifestyle", title: "30 days as a sea farer", story: ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolores nihil suscipit ullam amet voluptatibus laboriosam est hic beatae obcaecati perferendis earum explicabo dolorem, maxime, quidem officiis sequi modi aspernatur maiores fugit rerum eos null  temporibus. Quam exercitationem amet, repellat doloribus inventore quod delectus non suscipit, doloremque, rem excepturi dolor. Lorem ipsum dolor sit amet consectetur.` },
  { id: 4, img: makeup, beauty: "Beauty & Fashion", title: "The impact of beauty products on self esteeem of individuals", story: ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolores nihil suscipit ullam amet voluptatibus laboriosam est hic beatae obcaecati perferendis earum explicabo dolorem, maxime, quidem officiis sequi modi aspernatur maiores fugit rerum eos null  temporibus. Quam exercitationem amet, repellat doloribus inventore quod delectus non suscipit, doloremque, rem excepturi dolor. Lorem ipsum dolor sit amet consectetur.` },
  { id: 5, img: fire, beauty: "History", title: "The evolution of fire", story: ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolores nihil suscipit ullam amet voluptatibus laboriosam est hic beatae obcaecati perferendis earum explicabo dolorem, maxime, quidem officiis sequi modi aspernatur maiores fugit rerum eos null  temporibus. Quam exercitationem amet, repellat doloribus inventore quod delectus non suscipit, doloremque, rem excepturi dolor. Lorem ipsum dolor sit amet consectetur.` },
  { id: 6, img: ship, beauty: "Lifestyle", title: "30 days as a sea farer", story: ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolores nihil suscipit ullam amet voluptatibus laboriosam est hic beatae obcaecati perferendis earum explicabo dolorem, maxime, quidem officiis sequi modi aspernatur maiores fugit rerum eos null  temporibus. Quam exercitationem amet, repellat doloribus inventore quod delectus non suscipit, doloremque, rem excepturi dolor. Lorem ipsum dolor sit amet consectetur.` },
];
